
meta_name: "Fitseek"
meta_title: "Fitseek - The fitness App for lazy people!"
meta_description: "Fitseek is an app designed for fitness enthusiasts"
meta_image: "metapic.jpg" # should exist in `app/assets/images/`
